### PR TITLE
Fix python google style return type position

### PR DESCRIPTION
**Pull request by steven-lang**
The google style has the return type in the wrong position. See https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html for examples.

### CODE REVIEW

**Comment by kkoomen** [comment]
Hi,

Nice catch! If you fix the tests I'll merge immediately.

**Comment by kkoomen** [comment]
Your contribution has been released as [v1.5.1](https://github.com/kkoomen/vim-doge/tree/v1.5.1).

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.

**Comment by steven-lang** [comment]
Thanks! Sorry, I didn't check the tests.

**Comment by steven-lang** [comment]
Thanks! Sorry, I didn't check the tests.

**Pull request merged**
