### PR TITLE
fix(ruby): Fix ruby keyword arguments and without parentheses

### PR DESCRIPTION
**Pull request by weirongxu**
# Prelude

Thank you for helping out DoGe!

By contributing to DoGe you agree to the following statements **(Replace `[ ]` with `[x]` with those you agree with)**:
- [x] I have read and understood the [Contribution Guidelines](https://github.com/kkoomen/vim-doge/blob/master/CONTRIBUTING.md).
- [x] I have read and understood the [Code of Conduct](https://github.com/kkoomen/vim-doge/blob/master/CODE_OF_CONDUCT.md).

# Why this PR?

Fix ruby function without parentheses

And I let `parameters.match` support the use of arrays because using one regular expression can't satisfy my needs.

And I let `l:curr_line_raw` contains the `\n` because ruby needs to determine if there is a `\n`.

https://github.com/weirongxu/vim-doge/blob/4c43cd41cf5b099b93225a3e2616f2544d639a6e/autoload/doge/pattern.vim#L29

### CODE REVIEW

**Comment by kkoomen** [comment]
Hi.

Thanks for putting effort in the nice pull request, but you're making things more complicated then you need. The only solution you need is to allow ruby functions without parameters. The only thing you need to do is change [this](https://github.com/kkoomen/vim-doge/blob/master/ftplugin/ruby.vim#L45):

```rb
let s:function_and_class_method_pattern = doge#helpers#deepextend(s:pattern_base, {
\  'match': '\m^def\s\+\%([^=(!]\+\)[=!]\?\s*(\(.\{-}\))',
\  'tokens': ['parameters'],
\})
```

into this (notice the `match` regex has been adjusted)

```rb
let s:function_and_class_method_pattern = doge#helpers#deepextend(s:pattern_base, {
\  'match': '\m^def\s\+\%([^=(! ]\+\)[=!]\?\s*(\?\([^\n)]\+\))\?',
\  'tokens': ['parameters'],
\})
```

If you want to continue to do a PR then you can implement my fix and adjust tests to only this scenario. Otherwise I can fix it now if you want.

**Comment by weirongxu** [comment]
```
let s:function_and_class_method_pattern = doge#helpers#deepextend(s:pattern_base, {
\  'match': '\m^def\s\+\%([^=(! ]\+\)[=!]\?\s*(\?\([^\n)]\+\))\?',
\  'tokens': ['parameters'],
\})
```
This patch will not completely fix the problem

```ruby
def myFunc format
end

def params(p1, p2)
end
```
Generate doc on `def myFunc` will get wrong results

**Comment by kkoomen** [comment]
The following works:

```vim
let s:function_and_class_method_pattern = doge#helpers#deepextend(s:pattern_base, {
\  'match': '\m^def\s\+\%([^=(! ]\+\)[=!]\?\s*(\?\([^\n)]\{-}\))\?\s*end',
\  'tokens': ['parameters'],
\})

```

Any other scenarios?

**Comment by weirongxu** [comment]
OK, but still not support this
```ruby
def myFunc format
  val = 1
end
```

**Comment by weirongxu** [comment]
And another case to consider at the same time is that ruby parameters with parentheses support multiline.
```ruby
def myFunc(
  format,
  foo
)
end
```

**Comment by kkoomen** [comment]
>OK, but still not support this
>
>def myFunc format
>  val = 1
>end

I've added a strict pattern for the parameter format. This works.

```vim
let s:function_and_class_method_pattern = doge#helpers#deepextend(s:pattern_base, {
\  'match': '\m^def\s\+\%([^=(! ]\+\)[=!]\?\s*(\?\s*\(\(\%(&\?[[:alnum:]_]\+\%(\s*=\s*[^, ]\+\)\?\)\%(\s*,\s*\)\?\)*\)\s*)\?.\{-}end',
\  'tokens': ['parameters'],
\})
```

Anything else?

**Comment by weirongxu** [comment]
Thanks, it looks like could solve this issue, later I will add some tests for this.
Also, we should support the keyword parameter, https://thoughtbot.com/upcase/videos/ruby-keyword-arguments

**Comment by weirongxu** [comment]
It seems necessary to check `\n`, otherwise there seems to be can't support following code
```ruby
def myFunc
end
```

**Comment by kkoomen** [comment]
I allowed the use of [`'normalize': 0`](https://github.com/kkoomen/vim-doge/blob/5915891ca7ca578d05df2354db8ccc2fef12f5b7/ftplugin/ruby.vim#L48) in patterns which will not normalize the input (replacing `"\n"` with `' '`). Then I used `\n` as a check in the regex. This is a proper solution, since ruby is a big exception in it's language syntax.

All your tests are passing as well, thanks for adding them. If you don't have any other scenarios then I will merge soon.

**Comment by weirongxu** [comment]
Thank you so much, you can merge now.

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v2.2.6](https://github.com/kkoomen/vim-doge/tree/v2.2.6). Thanks a lot for your contribution. It has been appreciated a lot. 🙌

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

<hr />

@weirongxu Are you interested in translating 2 README files into Chinese?

**Comment by weirongxu** [comment]
> @weirongxu Are you interested in translating 2 README files into Chinese?

Sorry, no interest now, I need to do something else.

**Pull request merged**
