### PR TITLE
[Feature] Do not download binary if already downloaded

### PR DESCRIPTION
**Pull request by kkoomen**
See #155

### CODE REVIEW

**Comment by kkoomen** [comment]
@subnut I tested this locally which seems to work fine. Can you test this on Windows?

**Comment by subnut** [comment]
```patch
diff --git a/autoload/doge.vim b/autoload/doge.vim
index 2666353..30df14a 100644
--- a/autoload/doge.vim
+++ b/autoload/doge.vim
@@ -181,10 +181,10 @@ endfunction
 "" @public
 " Install the necessary dependencies.
 function! doge#install() abort
-  for l:filename in ['vim-doge', 'vim-dog.exe']
+  for l:filename in ['vim-doge', 'vim-doge.exe']
     let l:filepath = g:doge_dir . '/bin/' . l:filename
     if filereadable(l:filepath)
-      let l:binary_version = doge#helpers#trim(system(l:filepath . ' --version'))
+      let l:binary_version = doge#helpers#trim(system(shellescape(l:filepath) . ' --version'))
       let l:local_version = doge#helpers#trim(readfile(g:doge_dir . '/.version')[0])
       if l:binary_version ==# l:local_version
         echom '[DoGe] already using latest version, skipping binary download'

```

**Comment by subnut** [comment]
Please give me pre-compiled binaries (with the support for `--version`) for both Windows and Linux for checking.

**Comment by kkoomen** [comment]
@subnut you can create binaries yourself locally with `npm run build:binary -- node14-linux-x64` and `npm run build:binary:windows -- node14-win-x64`

**Comment by subnut** [comment]
```
❯ npm run build:binary -- node14-linux-x64

> vim-doge@3.5.1 build:binary /home/subhaditya/.plug ged/vim-doge
> rimraf build && ncc build ./src/index.ts -m -o build && ./scripts/build.sh "node14-linux-x64"

sh: rimraf: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! vim-doge@3.5.1 build:binary: `rimraf build && ncc build ./src/index.ts -m -o build && ./scripts/build.sh "node14-linux-x64"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vim-doge@3.5.1 build:binary script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/subhaditya/.npm/_logs/2020-11-15T14_18_31_981Z-debug.log
```

**Comment by subnut** [comment]
@kkoomen I am unable to build, see error above.

**Comment by subnut** [comment]
says `rimraf not available`
how to get it?

**Comment by kkoomen** [comment]
> says `ncc not available`
> 
> how to get it?

Run `npm install` obviously.

**Comment by subnut** [comment]
Thanks, that did it :+1:

Now I ran `vim-doge --version` to check the binary, but it gave this error -
```
❯ vim-doge --version
pkg/prelude/bootstrap.js:1616
        const res = ancestor.dlopen.apply(process, args);
                                    ^

Error: The module '/tmp/2598d8843a4cdd00fdecd7430a5022b396f7fbd38f03e8e630f188932e3b7033_tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 88. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at tryImporting (pkg/prelude/bootstrap.js:1616:37)
    at process.dlopen (pkg/prelude/bootstrap.js:1642:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1248:18)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1229:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.8460 (/snapshot/vim-doge/build/index.js)
    at __webpack_require__ (/snapshot/vim-doge/build/index.js)
```
Please help

---

> obviously

As I said before, I have **never** user `npm` or `nodejs`, so it's all alien stuff to me :smile:

**Comment by kkoomen** [comment]
I need some info from you in order to find your problem:
- what system are you using?
- what node version do you have locally? (please provide the output from `node --version`)
- what command did you use to generate the binary? Please provide the full command

**Comment by subnut** [comment]
- node version
```
❯ node --version
v15.2.0
```

- system
Arch Linux (64-bit)

- commands
```
❯ cd vim-doge
❯ npm install
❯ npm run build:binary -- node14-linux-x64
```

<br>

Command output -
```
❯ npm run build:binary -- node14-linux-x64

> vim-doge@3.5.1 build:binary /home/subhaditya/.config/nvim/plugged/vim-doge
> rimraf build && ncc build ./src/index.ts -m -o build && ./scripts/build.sh "node14-linux-x64"

ncc: Version 0.25.1
ncc: Compiling file index.js
ncc: Using typescript@4.0.5 (local user-provided)
   0kB  build/src/types.d.ts
   0kB  build/src/index.d.ts
   0kB  build/src/helpers.d.ts
   0kB  build/src/constants.d.ts
   0kB  build/src/parsers/custom-parser-service.interface.d.ts
   0kB  build/src/parsers/base-parser.service.d.ts
   1kB  build/src/parsers/typescript.service.d.ts
   1kB  build/src/parsers/ruby.service.d.ts
   1kB  build/src/parsers/python.service.d.ts
   1kB  build/src/parsers/php.service.d.ts
   1kB  build/src/parsers/lua.service.d.ts
   1kB  build/src/parsers/java.service.d.ts
   1kB  build/src/parsers/index.d.ts
   1kB  build/src/parsers/cpp.service.d.ts
   1kB  build/src/parsers/c.service.d.ts
   1kB  build/src/parsers/bash.service.d.ts
 160kB  build/build/Release/tree_sitter_lua_binding.node
 194kB  build/build/Release/tree_sitter_python_binding.node
 237kB  build/build/Release/tree_sitter_java_binding.node
 343kB  build/build/Release/tree_sitter_runtime_binding.node
 346kB  build/build/Release/tree_sitter_c_binding.node
 378kB  build/build/Release/tree_sitter_php_binding.node
 387kB  build/build/Release/tree_sitter_bash_binding.node
 412kB  build/index.js
 734kB  build/build/Release/tree_sitter_tsx_binding.node
 984kB  build/build/Release/tree_sitter_cpp_binding.node
1173kB  build/build/Release/tree_sitter_ruby_binding.node
5358kB  [3865ms] - ncc 0.25.1
> pkg@4.4.9
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_bash_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_c_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_cpp_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_java_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_lua_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_php_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_python_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_ruby_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_tsx_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '__webpack_require__.ab + 'build/Release/tree_sitter_runtime_binding.node''
  /home/subhaditya/.config/nvim/plugged/vim-doge/build/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
🎉  Done building vim-doge binaries
```

**Comment by kkoomen** [comment]
Weird, I don't know why you're running into that issue. The thing is that you need to build the binary on its corresponding system, as in: the Linux binary must be build on a Linux system and the same goes for Windows + MacOS, this does include the `npm install` command. You can't build something for Windows on a MacOS or Linux and vice versa.

I can do a pre-release later this week and let you test those.

**Comment by subnut** [comment]
OK! But when is this pre-release coming? Approximate date? :smile:

**Comment by kkoomen** [comment]
Approximate date: 10m from now haha. I was about to release it. Give me some minutes.

**Comment by kkoomen** [comment]
You can wait for [this action run](https://github.com/kkoomen/vim-doge/actions/runs/365977926) to be completed. Then you can pull from master and run `:call doge#install()` again to test it.

**Comment by kkoomen** [comment]
Excuse me, I forgot to add [this comment](https://github.com/kkoomen/vim-doge/pull/157#issuecomment-727567359). I'll add it immediately.

**Comment by kkoomen** [comment]
You can wait for [this action run](https://github.com/kkoomen/vim-doge/actions/runs/365988647) to be completed and test it with those binaries.

**Comment by subnut** [comment]
OK! I will test in linux right away, but Windows later (my dad's working on that PC right now :sweat_smile: )

**Comment by kkoomen** [comment]
@subnut v3.5.2-beta.1 works perfectly for me on MacOS.

**Comment by subnut** [comment]
@kkoomen Works in both Windows and Linux :+1:

**Comment by kkoomen** [comment]
Alright. I'm releasing v3.5.2 right now.

**Pull request merged**
