### PR TITLE
Add option to replace todo

### PR DESCRIPTION
**Pull request by vkasljevic**
# Prelude

Thank you for helping out DoGe!

By contributing to DoGe you agree to the following statements **(Replace `[ ]` with `[x]` with those you agree with)**:
- [x] I have read and understood the [Contribution Guidelines](https://github.com/kkoomen/vim-doge/blob/master/CONTRIBUTING.md).
- [x] I have read and understood the [Code of Conduct](https://github.com/kkoomen/vim-doge/blob/master/CODE_OF_CONDUCT.md).

# Why this PR?
This PR enables user to use configurable placeholder in generated documentation.
For ex. instead of using `TODO` as placeholder I could use `TODO(<user>)`.

### CODE REVIEW

**Comment by kkoomen** [comment]
Thanks for putting quite some effort into this. However, I don't understand why you want to use `TODO(<user>)` to be set globally for everything? This would, for example, end up in:

```python
def myMethod(self: MyClass, p1: Sequence[T]) -> Generator[int, float, str]:
    """
    TODO(<user>)

    :param self MyClass: TODO(<user>)
    :param p1 Sequence[T]: TODO(<user>)
    :rtype Generator[int, float, str]: TODO(<user>)
    """
    pass
```

I'm not seeing in _why_ this would be useful.

**Comment by vkasljevic** [comment]
Well, my case is that I have script for listing TODOs that matches only my `TODO(<user>)` because I work on large codebase with a lot of other people. I did this so that they could play along nicely, but I thought that someone else might have same inconvenience. Also, I don't have to keep my fork up to date.

As for the adding context to TODOs, it doesn't seem like that much extra work, I could add it if you want.

**Comment by kkoomen** [comment]
I will add the context feature for now by myself, however I don't think this is something DoGe needs. If you want to give your descriptions more context for certain users you work with then this is a content issue and up to the user to add.

I'll close the issue for now. Thanks for submitting your idea.

**Comment by kkoomen** [comment]
The TODO context support is released in [v1.4.0](https://github.com/kkoomen/vim-doge/tree/v1.4.0).

**Pull request closed without merging**
