### PR TITLE
Deactivate doge if no placeholders left

### PR DESCRIPTION
**Pull request by mg979**
Check on InsertLeave if there are placeholders left, if not, deactivate
doge.

# Prelude

Thank you for helping out DoGe!

By contributing to DoGe you agree to the following statements **(Replace `[ ]` with `[x]` with those you agree with)**:
- [ ] I have read and understood the [Contribution Guidelines](https://github.com/kkoomen/vim-doge/blob/master/CONTRIBUTING.md).
- [ ] I have read and understood the [Code of Conduct](https://github.com/kkoomen/vim-doge/blob/master/CODE_OF_CONDUCT.md).

# Why this PR?

Before this PR, after the last placeholder was consumed, the first Tab keypress would still use doge mapping, which is undesiderable. It checks on InsertLeave, so that if the placeholder is reached, but not consumed, doge remains active.

### CODE REVIEW

**Comment by kkoomen** [comment]
I added proper documentation to the function, adjusted the function name to be more global and I did use the helpers function `doge#helpers#count()` to simplify the code. I moved your function code to the `TextChangedI` callback function and there it will properly update the new `todo_count` variable in `b:doge_interactive`. Your function will then only check if the amount of TODO items is `0` and will deactivate when the statement evaluates.

Any suggestions / recommendations or possible drawbacks towards my implementation I haven't thought about?

**Comment by mg979** [comment]
Unfortunately this way TextChanged doesn't work, because if placeholders are deleted in normal mode that counter won't be updated (because it's updated when jumping). I tried a similar approach in my very first PR (checking the count) and I didn't like it. If you want it to work with TextChanged I don't think there are alternatives to search for the pattern in the autocommand, but it's not that there are performance issues or anything, so I don't see the problem.

**Comment by kkoomen** [comment]
Agree, I haven't thought about that, but wasn't for of this while I implemented it. I changed the implementation by moving the update part in the `TextChangedI` function to your function. This works perfectly as I see for now. Agree?

**Comment by mg979** [comment]
You sure it's working now? tabbing in insert mode seems broken to me.

**Comment by kkoomen** [comment]
I do have the same. Didn't test insert-mode last time. This has to do with the `doge#helpers#count` function. It seems to be the `let l:cnt = execute(l:range . 's/' . a:word . '//gn')` line and I have no idea why. If I remove this and just `return 4` then it doesn't occur that the count returns `0`.

**Comment by mg979** [comment]
I think you should learn a thing or two from [this guy](https://www.youtube.com/watch?v=seLT7M3OAgk&feature=youtu.be&t=393). Then maybe you can tell me what was wrong with the function I wrote :).

**Comment by kkoomen** [comment]
I reverted back to your previous commit. The reason I prefer my version is because your code is redundant while there is a helper function that _should_ work, but the helper function is not being called at the auto-command`InsertLeave` so I'll just leave it at your version. That's fine for now.

**Pull request merged**
